version: "3.8"

services:
  api1:
    image: gustavocs789/rinha-de-backend-2023-q3-api:latest
    hostname: api1
    restart: always
    env_file:
      - .env
    environment:
      - PORT=${PORT}
      - POSTGRES_HOST=${POSTGRES_HOST}
      - POSTGRES_PORT=${POSTGRES_PORT}
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - DATABASE_URL=${DATABASE_URL}
    networks:
      - rinha-de-backend-network
    expose:
      - ${PORT}
    depends_on:
      - database_pg
    deploy:
      resources:
        limits:
          cpus: "0.25"
          memory: "0.5GB"

  api2:
    image: gustavocs789/rinha-de-backend-2023-q3-api:latest
    hostname: api2
    restart: always
    env_file:
      - .env
    environment:
      - PORT=${PORT}
      - POSTGRES_HOST=${POSTGRES_HOST}
      - POSTGRES_PORT=${POSTGRES_PORT}
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    expose:
      - ${PORT}
    networks:
      - rinha-de-backend-network
    depends_on:
      - database_pg
    deploy:
      resources:
        limits:
          cpus: "0.25"
          memory: "0.5GB"

  database_pg:
    image: postgres
    restart: always
    env_file:
      - .env
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    ports:
      - ${POSTGRES_PORT}:${POSTGRES_PORT}
    networks:
      - rinha-de-backend-network
    deploy:
      resources:
        limits:
          cpus: "0.75"
          memory: "1.5GB"

  cache_redis:
    image: redis:7.0.5
    restart: always
    command: redis-server --requirepass ${REDIS_PASSWORD}
    ports:
      - '6379:6379'

  nginx:
    image: nginx:latest
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - "9999:9999"
    networks:
      - rinha-de-backend-network
    depends_on:
      - api1
      - api2
    deploy:
      resources:
        limits:
          cpus: "0.25"
          memory: "0.5GB"

networks:
  rinha-de-backend-network:
    driver: bridge
