version: "3.8"

services:
  database_pg:
    image: postgres
    container_name: database_pg
    restart: always
    env_file:
      - .env
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    ports:
      - 5432:5432
    deploy:
      resources:
        limits:
          cpus: "0.75"
          memory: "1.5GB"
