version: "3.8"

services:
  api1:
    image: gustavocs789/rinha-de-backend-2023-q3-api:latest
    hostname: api1
    restart: always
    env_file:
      - .env
    environment:
      - PORT=${PORT}
      - POSTGRES_HOST=${POSTGRES_HOST}
      - POSTGRES_PORT=${POSTGRES_PORT}
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    depends_on:
      - database_pg
    expose:
      - ${PORT}
    deploy:
      resources:
        limits:
          cpus: "0.25"
          memory: "0.5GB"

  api2:
    image: gustavocs789/rinha-de-backend-2023-q3-api:latest
    hostname: api2
    restart: always
    env_file:
      - .env
    environment:
      - PORT=${PORT}
      - POSTGRES_HOST=${POSTGRES_HOST}
      - POSTGRES_PORT=${POSTGRES_PORT}
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    depends_on:
      - database_pg
    expose:
      - ${PORT}
    deploy:
      resources:
        limits:
          cpus: "0.25"
          memory: "0.5GB"

  database_pg:
    image: postgres
    restart: always
    env_file:
      - .env
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    ports:
      - ${POSTGRES_PORT}:${POSTGRES_PORT}
    volumes:
      - ./start.sql:/docker-entrypoint-initdb.d/start.sql
    deploy:
      resources:
        limits:
          cpus: "0.75"
          memory: "1.5GB"

  nginx:
    image: nginx:latest
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - "9999:9999"
    depends_on:
      - api1
      - api2
    deploy:
      resources:
        limits:
          cpus: "0.25"
          memory: "0.5GB"
